Repository sdd-manifesto/manifesto, pull requests merged in 2018-11, with the labels that each got.

#1 Add Kenny to the list of initial authors
  README.md
Labels: enhancement

#2 Typo in 'observable':'debug' section
  README.md
Labels: auto-merge:on-approve, changelog:fixed, manifesto

#6 Acknowledge prior art
  README.md
Labels: auto-merge:on-approve, changelog:added, manifesto

#7 CSS updates for signature list page
  app/public/css/main.css
  app/sass/base/_base.scss
  app/sass/base/_typography.scss
  app/sass/globals/_footer.scss
  app/sass/pages/_signatures.scss
  app/views/layouts/main.handlebars
  app/views/signatures.handlebars
  package.json
Labels: app, changelog:changed, enhancement
